# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=50)),
                ('writters', models.CharField(max_length=50)),
                ('length', models.DurationField()),
                ('country', models.CharField(max_length=50)),
                ('add_date', models.DateField()),
                ('image', models.FileField(upload_to='images/')),
                ('trailer_url', models.URLField()),
            ],
        ),
    ]
